[package]
name = "nyannix"
version = "0.1.0"
edition = "2021"

[dependencies]
spin = "0.9.8"
heapless = "0.7"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = true

[build-dependencies]
cc = "1.0"
